#服务端口
server:
  port: 8085
#服务名称
spring:
  application:
    name: test-freemarker
  data:
    mongodb:
#      使用springboot提供的默认配置
#      uri:  mongodb:// root:123@localhost:27017
      database: xc_cms
  freemarker:
    cache: false  #关闭模板缓存,方便测试
    settings:
      template_update_delay: 0 #设置模板更新延迟时间,设置0为立即检查,如果时间大于0会有缓存不方便进行模板测试
